from collections.abc import Sequence

from ._types import ArrayInterface, ArrayLike, BlendMode, ExprLike, PieceData, RecipeLike, Rgba, ShapeLike

__version__: str

free_threaded: bool

class PuzzleError(Exception): ...

class Fraction:
    def __init__(self, numerator: int, denominator: int = 1) -> None: ...
    @property
    def numerator(self) -> str: ...
    @property
    def denominator(self) -> str: ...
    def __add__(self, other: Fraction) -> Fraction: ...
    def __sub__(self, other: Fraction) -> Fraction: ...
    def __mul__(self, other: Fraction) -> Fraction: ...
    def __truediv__(self, other: Fraction) -> Fraction: ...
    def __neg__(self) -> Fraction: ...
    def __abs__(self) -> Fraction: ...
    def __float__(self) -> float: ...
    def __lt__(self, other: Fraction) -> bool: ...
    def __le__(self, other: Fraction) -> bool: ...
    def __gt__(self, other: Fraction) -> bool: ...
    def __ge__(self, other: Fraction) -> bool: ...

class Real:
    @staticmethod
    def from_int(n: int) -> Real: ...
    @staticmethod
    def parse(expr: str) -> Real: ...
    def root(self, k: int) -> Real: ...
    def sign(self) -> int: ...
    def interval(self) -> tuple[Fraction, Fraction]: ...
    @property
    def field(self) -> str: ...
    def __add__(self, other: Real) -> Real: ...
    def __sub__(self, other: Real) -> Real: ...
    def __mul__(self, other: Real) -> Real: ...
    def __truediv__(self, other: Real) -> Real: ...
    def __neg__(self) -> Real: ...
    def __abs__(self) -> Real: ...
    def __float__(self) -> float: ...
    def __lt__(self, other: Real) -> bool: ...
    def __le__(self, other: Real) -> bool: ...
    def __gt__(self, other: Real) -> bool: ...
    def __ge__(self, other: Real) -> bool: ...

class Image:
    def __init__(self, width: int, height: int, color: Rgba = ...) -> None: ...
    @staticmethod
    def from_bytes(width: int, height: int, data: bytes) -> Image: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride(self) -> int: ...
    @property
    def __array_interface__(self) -> ArrayInterface: ...
    def __len__(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    def to_png(self) -> bytes: ...
    def save(self, path: str) -> None: ...
    def pixel(self, x: int, y: int) -> Rgba: ...
    def set_pixel(self, x: int, y: int, color: Rgba) -> None: ...
    def fill(self, color: Rgba) -> None: ...
    def fill_rect(self, x: int, y: int, width: int, height: int, color: Rgba, mode: BlendMode = ...) -> None: ...
    def blit(
        self,
        src: Image,
        x: int = 0,
        y: int = 0,
        src_x: int = 0,
        src_y: int = 0,
        src_width: int | None = None,
        src_height: int | None = None,
        mode: BlendMode = ...,
    ) -> None: ...
    def draw_text(
        self, x: int, y: int, text: str, color: Rgba = ..., scale: int = 1, mode: BlendMode = ..., center: bool = False
    ) -> int: ...
    @staticmethod
    def text_size(text: str, scale: int = 1) -> tuple[int, int]: ...
    @staticmethod
    def fit_text(text: str, max_width: int, scale: int = 1) -> str: ...
    def downsample(self, factor: int) -> Image: ...
    def resized(self, width: int, height: int) -> Image: ...
    def copy(self) -> Image: ...

class Shape:
    @staticmethod
    def polyhedron(name: str, size: ExprLike | None = None) -> Shape: ...
    @staticmethod
    def plane(a: ExprLike, b: ExprLike, c: ExprLike, d: ExprLike) -> Shape: ...
    @staticmethod
    def parse(text: str) -> Shape: ...
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def size(self) -> str: ...
    @property
    def coefficients(self) -> tuple[str, str, str] | None: ...
    def offset(self) -> Real: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Recipe:
    def __init__(self, shell: Sequence[Shape] = ..., cuts: Sequence[Shape] = ...) -> None: ...
    @staticmethod
    def parse(query: str) -> Recipe: ...
    @staticmethod
    def named(name: str) -> Recipe: ...
    @property
    def shell(self) -> list[Shape]: ...
    @property
    def cuts(self) -> list[Shape]: ...
    @property
    def query(self) -> str: ...
    def with_shell(self, shell: Sequence[Shape]) -> Recipe: ...
    def with_cuts(self, cuts: Sequence[Shape]) -> Recipe: ...
    def adding_cuts(self, cuts: Sequence[Shape]) -> Recipe: ...
    def build(self) -> Puzzle: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Grip:
    @property
    def index(self) -> int: ...
    @property
    def axis(self) -> tuple[float, float, float]: ...
    @property
    def offset(self) -> float: ...
    @property
    def plane(self) -> str: ...
    @property
    def piece_count(self) -> int: ...
    @property
    def other_count(self) -> int: ...

class Puzzle:
    def __init__(
        self,
        recipe: RecipeLike | None = None,
        *,
        shell: ShapeLike | Sequence[ShapeLike] | None = None,
        cuts: ShapeLike | Sequence[ShapeLike] | None = None,
        background: Rgba | None = None,
        supersample: int | None = None,
        show_arrows: bool | None = None,
        show_edges: bool | None = None,
        show_pieces: bool | None = None,
        line_width: float | None = None,
        fov: float | None = None,
        distance: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
        seed: int | None = None,
        scramble: int | None = None,
    ) -> None: ...
    @staticmethod
    def named(name: str) -> Puzzle: ...
    @staticmethod
    def from_recipe(recipe: Recipe) -> Puzzle: ...
    @property
    def piece_count(self) -> int: ...
    @property
    def field(self) -> str: ...
    @property
    def scale(self) -> float: ...
    @property
    def recipe(self) -> Recipe: ...
    @property
    def query(self) -> str: ...
    def piece(self, index: int) -> PieceData: ...
    @property
    def grip_count(self) -> int: ...
    def grips(self) -> list[Grip]: ...
    def grip(self, index: int) -> str: ...
    def stops(self, index: int) -> list[float]: ...
    def turn(self, index: int, direction: int = 1, *, repeat: int = 1) -> None: ...
    def turn_to(self, index: int, stop: int) -> None: ...
    def undo(self) -> bool: ...
    @property
    def history_length(self) -> int: ...
    def settle(self) -> None: ...
    def scramble(self, count: int = 10) -> None: ...
    def move_random(self) -> None: ...
    def seed(self, seed: int) -> None: ...
    @property
    def move_count(self) -> int: ...
    def restore(self) -> bool: ...
    def reset(self) -> None: ...
    def stickers(self) -> list[int]: ...
    def sticker_positions(self) -> list[tuple[float, float, float]]: ...
    def sticker_ids(self) -> list[int]: ...
    @property
    def solved_stickers(self) -> list[int]: ...
    @property
    def sticker_count(self) -> int: ...
    @property
    def color_count(self) -> int: ...
    @property
    def palette(self) -> list[int]: ...
    @property
    def is_solved(self) -> bool: ...
    def ground_atoms(self) -> list[tuple[str, str, str]]: ...
    @property
    def actions(self) -> list[str]: ...
    @property
    def action_count(self) -> int: ...
    @property
    def grip_names(self) -> list[str]: ...
    def action_index(self, name: str) -> int | None: ...
    def action_grip(self, action: int) -> int | None: ...
    def apply_action(self, action: int) -> bool: ...
    def action_mask(self) -> list[bool]: ...
    def action_permutations(self) -> Array | None: ...
    def apply(self, moves: str) -> int: ...
    def advance(self, dt_ms: float = 16.0) -> None: ...
    def render(
        self,
        width: int = 512,
        height: int = 512,
        *,
        background: Rgba | None = None,
        supersample: int | None = None,
        show_arrows: bool | None = None,
        show_edges: bool | None = None,
        show_pieces: bool | None = None,
        line_width: float | None = None,
        fov: float | None = None,
        distance: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
    ) -> Image: ...
    def frame(self, dt_ms: float = 16.0, width: int = 512, height: int = 512) -> Image: ...
    @property
    def animating(self) -> bool: ...
    background: Rgba
    supersample: int
    show_arrows: bool
    show_edges: bool
    show_pieces: bool
    line_width: float
    fov: float
    distance: float
    camera_position: tuple[float, float, float]
    camera_up: tuple[float, float, float]
    camera_target: tuple[float, float, float]
    def look_from(self, yaw: float, pitch: float, distance: float | None = None) -> None: ...
    def orbit(self, dx: float, dy: float) -> None: ...
    def pointer_move(self, x: float, y: float) -> None: ...
    def pointer_down(self, x: float, y: float) -> bool: ...
    def pointer_up(self, x: float, y: float) -> tuple[int, int] | None: ...
    def arrow_at(self, x: float, y: float) -> int | None: ...
    @property
    def hovered_arrow(self) -> int | None: ...
    def clear_hover(self) -> None: ...
    @property
    def arrow_count(self) -> int: ...

class Array:
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def typestr(self) -> str: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def __array_interface__(self) -> ArrayInterface: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int | float | bool | list[int] | list[float] | list[bool]: ...
    def tolist(self) -> list[int] | list[float] | list[bool]: ...
    def to_bytes(self) -> bytes: ...

class Layout:
    def __init__(self, recipe: RecipeLike | None = None) -> None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def is_cube(self) -> bool: ...
    @property
    def facelet_count(self) -> int: ...
    @property
    def face_count(self) -> int: ...
    @property
    def face_sizes(self) -> Array: ...
    @property
    def move_count(self) -> int: ...
    @property
    def faces(self) -> list[str]: ...
    @property
    def move_names(self) -> list[str]: ...
    @property
    def moves(self) -> Array: ...
    @property
    def actions(self) -> list[int | None]: ...
    @property
    def inverses(self) -> list[int | None]: ...
    @property
    def facelet_of_slot(self) -> Array: ...
    @property
    def slot_of_facelet(self) -> Array: ...
    @property
    def goal_colors(self) -> Array: ...
    @property
    def goal_ids(self) -> Array: ...
    def with_moves(self, sequences: Sequence[Sequence[int]]) -> Layout: ...
    def move_index(self, name: str) -> int | None: ...
    def moves_to_actions(self, moves: Sequence[int]) -> list[int]: ...
    def inverse_moves(self, moves: ArrayLike | Sequence[int]) -> Array: ...
    def to_facelets(self, states: ArrayLike | Sequence[int] | bytes) -> Array: ...
    def to_facelet_ids(self, ids: ArrayLike | Sequence[int]) -> Array: ...
    def from_facelets(self, facelets: ArrayLike | Sequence[int] | bytes) -> Array: ...
    def next_states(self, states: ArrayLike | Sequence[int] | bytes, moves: int | Sequence[int]) -> Array: ...
    def trajectories(
        self, steps: int | tuple[int, int] | Sequence[int], count: int | None = None, *, seed: int = 0
    ) -> tuple[Array, Array]: ...
    def scrambled(self, count: int, depth: int | tuple[int, int] | Sequence[int], *, seed: int = 0) -> Array: ...
    def one_hot(self, facelets: ArrayLike | Sequence[int] | bytes) -> Array: ...
    def solved(self, facelets: ArrayLike | Sequence[int] | bytes) -> Array: ...
    def text(self, facelets: ArrayLike | Sequence[int] | bytes) -> str: ...

class PuzzleBatch:
    def __init__(
        self,
        recipe: RecipeLike,
        count: int,
        *,
        seed: int | None = None,
        scramble: int | None = None,
        background: Rgba | None = None,
        supersample: int | None = None,
        show_edges: bool | None = None,
        show_pieces: bool | None = None,
        line_width: float | None = None,
        fov: float | None = None,
        distance: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    @property
    def query(self) -> str: ...
    @property
    def is_tabular(self) -> bool: ...
    @property
    def sticker_count(self) -> int: ...
    @property
    def action_count(self) -> int: ...
    @property
    def color_count(self) -> int: ...
    @property
    def actions(self) -> list[str]: ...
    @property
    def grip_names(self) -> list[str]: ...
    @property
    def solved_stickers(self) -> list[int]: ...
    @property
    def palette(self) -> list[int]: ...
    def action_index(self, name: str) -> int | None: ...
    def seed(self, index: int, seed: int) -> None: ...
    def seed_all(self, seed: int) -> None: ...
    def reset(self, *, scramble: int = 0) -> None: ...
    def reset_one(self, index: int, *, scramble: int = 0) -> None: ...
    def reset_where(self, which: Sequence[bool] | Sequence[int] | None = None, *, scramble: int = 0) -> None: ...
    def solve(self, which: Sequence[bool] | Sequence[int] | None = None) -> None: ...
    def scramble(self, depth: int | Sequence[int]) -> None: ...
    def step(self, actions: ArrayLike | Sequence[int]) -> tuple[Array, Array]: ...
    def undo(self, which: Sequence[bool] | Sequence[int] | None = None) -> Array: ...
    def apply(self, moves: str) -> int: ...
    def history(self, index: int) -> list[int]: ...
    @property
    def permutations(self) -> Array | None: ...
    @property
    def move_counts(self) -> list[int]: ...
    def set_states(self, states: ArrayLike | Sequence[int] | bytes, *, ids: bool = False) -> None: ...
    def set_facelets(self, layout: Layout, facelets: ArrayLike | Sequence[int] | bytes) -> None: ...
    def observations(self) -> Array: ...
    def sticker_ids(self) -> Array: ...
    def one_hot(self) -> Array: ...
    def action_masks(self) -> Array: ...
    def solved(self) -> Array: ...
    def render(
        self, width: int = 256, height: int = 256, *, channels: int = 4, channels_first: bool = False, dtype: str = "u1"
    ) -> Array: ...
    def render_states(
        self,
        states: ArrayLike | Sequence[int] | bytes,
        width: int = 256,
        height: int = 256,
        *,
        channels: int = 4,
        channels_first: bool = False,
        dtype: str = "u1",
    ) -> Array: ...
    def facelets(self, layout: Layout) -> Array: ...
    def facelet_ids(self, layout: Layout) -> Array: ...
    def frames(self, width: int = 256, height: int = 256) -> list[Image]: ...
    @property
    def camera(
        self,
    ) -> tuple[tuple[float, float, float], tuple[float, float, float], tuple[float, float, float], float] | None: ...
    def configure(
        self,
        *,
        background: Rgba | None = None,
        supersample: int | None = None,
        show_edges: bool | None = None,
        show_pieces: bool | None = None,
        line_width: float | None = None,
        fov: float | None = None,
        distance: float | None = None,
        yaw: float | None = None,
        pitch: float | None = None,
        camera_position: tuple[float, float, float] | None = None,
        camera_target: tuple[float, float, float] | None = None,
        camera_up: tuple[float, float, float] | None = None,
    ) -> None: ...

def catalog() -> list[tuple[str, str, str, str]]: ...
def polyhedra() -> list[tuple[str, str]]: ...
def evaluate(expr: str) -> Real: ...
def factor_polynomial(coefficients: Sequence[int]) -> list[list[str]]: ...
def build_many(recipes: Sequence[RecipeLike]) -> list[Puzzle]: ...
def render_many(
    recipes: Sequence[RecipeLike],
    width: int = 512,
    height: int = 512,
    *,
    background: Rgba = ...,
    supersample: int = 2,
    show_arrows: bool = False,
    show_edges: bool = True,
    scramble: int = 0,
    seed: int | None = None,
    distance: float | None = None,
    yaw: float = 0.0,
    pitch: float = 0.0,
) -> list[Image]: ...
def thread_count() -> int: ...
def jumbles(recipe: RecipeLike) -> bool: ...
def non_jumbling() -> list[str]: ...
