//! The catalog of named puzzles: `(name, family, kind, recipe)` for each.
//!
//! Generated data. Do not edit by hand.

/// `(name, family, kind, recipe)` for each cataloged puzzle.
pub static CATALOG: &[(&str, &str, &str, &str)] = &[
    (
        "Halpern-Meier Pyramid",
        "Tetrahedra",
        "Face/corner-turning",
        "?shell=T$1&cut=T$0",
    ),
    (
        "Pyraminx (no tips)",
        "Tetrahedra",
        "Face/corner-turning",
        "?shell=T$1&cut=T$-1/3",
    ),
    (
        "Pyraminx",
        "Tetrahedra",
        "Face/corner-turning",
        "?shell=T$1&cut=T$-1/3&cut=T$-5/3",
    ),
    (
        "Pyramiddle",
        "Tetrahedra",
        "Face/corner-turning",
        "?shell=T$1&cut=T$-7/12",
    ),
    (
        "Master Pyraminx",
        "Tetrahedra",
        "Face/corner-turning",
        "?shell=T$1&cut=T$-2&cut=T$-1&cut=T$0",
    ),
    ("Pyramorphix", "Tetrahedra", "Edge-turning", "?shell=T$sqrt(2)&cut=C$0"),
    (
        "Mastermorphix",
        "Tetrahedra",
        "Edge-turning",
        "?shell=T$sqrt(2)&cut=C$1/5",
    ),
    (
        "Mastermorphynx",
        "Tetrahedra",
        "Edge-turning",
        "?shell=T$sqrt(2)&cut=C$1/3",
    ),
    ("2x2x2 Cube", "Cubes", "Face-turning", "?shell=C$1&cut=C$0"),
    ("Rubik's Cube (3x3x3)", "Cubes", "Face-turning", "?shell=C$1&cut=C$1/3"),
    ("4x4x4 Cube", "Cubes", "Face-turning", "?shell=C$1&cut=C$0&cut=C$1/2"),
    ("5x5x5 Cube", "Cubes", "Face-turning", "?shell=C$1&cut=C$1/5&cut=C$3/5"),
    (
        "6x6x6 Cube",
        "Cubes",
        "Face-turning",
        "?shell=C$1&cut=C$0&cut=C$1/3&cut=C$2/3",
    ),
    (
        "7x7x7 Cube",
        "Cubes",
        "Face-turning",
        "?shell=C$1&cut=C$1/7&cut=C$3/7&cut=C$5/7",
    ),
    ("Skewb", "Cubes", "Corner-turning", "?shell=C$sqrt(2)/3&cut=O$0"),
    (
        "Master Skewb",
        "Cubes",
        "Corner-turning",
        "?shell=C$sqrt(2)/3&cut=O$1/6",
    ),
    ("Dino Cube", "Cubes", "Corner-turning", "?shell=C$sqrt(2)/3&cut=O$1/3"),
    ("Compy Cube", "Cubes", "Corner-turning", "?shell=C$sqrt(2)/3&cut=O$1/2"),
    (
        "24-Cube / Little Chop",
        "Cubes",
        "Edge-turning",
        "?shell=C$3*sqrt(2)/4&cut=jC$0",
    ),
    (
        "Master Little Chop",
        "Cubes",
        "Edge-turning",
        "?shell=C$3*sqrt(2)/4&cut=jC$1/6",
    ),
    ("DeCETH", "Cubes", "Edge-turning", "?shell=C$3*sqrt(2)/4&cut=jC$1/4"),
    ("Quad-X", "Cubes", "Edge-turning", "?shell=C$3*sqrt(2)/4&cut=jC$1/3"),
    (
        "Helicopter Cube",
        "Cubes",
        "Edge-turning",
        "?shell=C$3*sqrt(2)/4&cut=jC$1/2",
    ),
    (
        "Master Helicopter",
        "Cubes",
        "Edge-turning",
        "?shell=C$3*sqrt(2)/4&cut=jC$1/2&cut=jC$3/4",
    ),
    ("Skewb Diamond", "Octahedra", "Face-turning", "?shell=O$1&cut=O$0"),
    ("FTO", "Octahedra", "Face-turning", "?shell=O$1&cut=O$1/3"),
    ("Dino-Octa", "Octahedra", "Face-turning", "?shell=O$1&cut=O$1/2"),
    (
        "Master FTO",
        "Octahedra",
        "Face-turning",
        "?shell=O$1&cut=O$0&cut=O$1/2",
    ),
    (
        "5-Layer FTO",
        "Octahedra",
        "Face-turning",
        "?shell=O$1&cut=O$1/5&cut=O$3/5",
    ),
    (
        "PyraDiamond (wrong colors)",
        "Octahedra",
        "Corner-turning",
        "?shell=O$sqrt(2)/2&cut=C$0",
    ),
    (
        "Magic Octahedron (no tips)",
        "Octahedra",
        "Corner-turning",
        "?shell=O$sqrt(2)/2&cut=C$1/3",
    ),
    (
        "Magic Octahedron",
        "Octahedra",
        "Corner-turning",
        "?shell=O$sqrt(2)/2&cut=C$1/3&cut=C$2/3",
    ),
    ("24-Octahedron", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$0"),
    ("Solar Octahedron", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$1/8"),
    ("Unknown", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$2/9"),
    ("Unknown", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$4/15"),
    ("Eitan's ETO", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$1/3"),
    ("Unknown", "Octahedra", "Edge-turning", "?shell=O$1&cut=jC$4/9"),
    ("Pentultimate", "Dodecahedra", "Face-turning", "?shell=D$1&cut=D$0"),
    ("Starminx", "Dodecahedra", "Face-turning", "?shell=D$1&cut=D$sqrt(5)-2"),
    (
        "Pyraminx Crystal",
        "Dodecahedra",
        "Face-turning",
        "?shell=D$1&cut=D$1/sqrt(5)",
    ),
    (
        "Megaminx",
        "Dodecahedra",
        "Face-turning",
        "?shell=D$1&cut=D$2/(sqrt(5)+1)",
    ),
    ("Chopasaurus", "Dodecahedra", "Corner-turning", "?shell=D$1&cut=I$0"),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(7-3*sqrt(5))/2",
    ),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(-1+sqrt(5))/6",
    ),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(5-sqrt(5))/10",
    ),
    (
        "Starminx III",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(-1+sqrt(5))/2",
    ),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(15+sqrt(5))/22",
    ),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(3-sqrt(5))/6",
    ),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(5+7*sqrt(5))/22",
    ),
    ("Pentagram", "Dodecahedra", "Corner-turning", "?shell=D$1&cut=I$1"),
    (
        "Unknown",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(5+3*sqrt(5))/10",
    ),
    (
        "Dino Dodecahedron",
        "Dodecahedra",
        "Corner-turning",
        "?shell=D$1&cut=I$(5-sqrt(5))/2",
    ),
    ("Big Chop", "Dodecahedra", "Edge-turning", "?shell=D$1&cut=jD$0"),
    (
        "Starminx II",
        "Dodecahedra",
        "Edge-turning",
        "?shell=D$1&cut=jD$(5-sqrt(5))/5",
    ),
    (
        "Solarminx",
        "Dodecahedra",
        "Edge-turning",
        "?shell=D$1&cut=jD$(6*sqrt(5)+20)/55",
    ),
    (
        "Dodecacopter",
        "Dodecahedra",
        "Edge-turning",
        "?shell=D$1&cut=jD$(sqrt(5)+5)/10",
    ),
    (
        "Radio Chop (Radiolarian 15)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$0",
    ),
    (
        "Radiolarian \"13.5\"",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(5-2*sqrt(5))/5",
    ),
    (
        "Radio Gem (Radiolarian 13)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(-3+2*sqrt(5))/11",
    ),
    (
        "Radio Nebula (Radiolarian 12)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(4-sqrt(5))/11",
    ),
    (
        "Radio Star (Radiolarian 11)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$-2+sqrt(5)",
    ),
    (
        "Radio Crystal (Radiolarian 9)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$1/3",
    ),
    (
        "Radio Jam (Radiolarian 8)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$sqrt(5)/5",
    ),
    (
        "Radio Jewel (Radiolarian 7)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$5-2*sqrt(5)",
    ),
    (
        "Cat's Cradle (Radiolarian 5)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(4+sqrt(5))/11",
    ),
    (
        "Radiolarian 4",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(-1+sqrt(5))/2",
    ),
    (
        "Radiolarian 3",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$(3+2*sqrt(5))/11",
    ),
    (
        "Circo-Radiolarian (Radiolarian 2)",
        "Icosahedra",
        "Face-turning",
        "?shell=I$1&cut=I$sqrt(5)/3",
    ),
    (
        "Icosamate",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$0",
    ),
    (
        "Master Icosamate",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/10",
    ),
    (
        "Regular Astrominx",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/6",
    ),
    (
        "Astrominx",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/4",
    ),
    (
        "Dogic (wrong colors)",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/2",
    ),
    (
        "Icosaminx",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/2+1/2",
    ),
    (
        "Tutt's Icosaminx (no tips)",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/2+2/3",
    ),
    (
        "Tutt's Icosaminx",
        "Icosahedra",
        "Corner-turning",
        "?shell=I$sqrt(5)+2&cut=D$(sqrt(5)+1)/2+2/3&cut=D$(sqrt(5)+1)/2+4/3",
    ),
    (
        "Deep-cut edge-turning icosahedron",
        "Icosahedra",
        "Edge-turning",
        "?shell=I$1&cut=jD$0",
    ),
    (
        "Jumble Prism (wrong colors)",
        "Other",
        "Corner-turning prisms",
        "?shell=P3$1&cut=dP3$1/4",
    ),
    (
        "Shallow Jumble Prism (with centers)",
        "Other",
        "Corner-turning prisms",
        "?shell=P3$1&cut=dP3$3/5",
    ),
    (
        "Curvy Shallow Jumble Prism",
        "Other",
        "Corner-turning prisms",
        "?shell=P3$1&cut=dP3$3/4",
    ),
    (
        "Edge of Insanity",
        "Other",
        "Face-turning dipyramids",
        "?shell=dP3$1&cut=dP3$-1/2",
    ),
    (
        "Shallower Madness",
        "Other",
        "Face-turning dipyramids",
        "?shell=dP3$1&cut=dP3$-1/5",
    ),
    (
        "More Madness",
        "Other",
        "Face-turning dipyramids",
        "?shell=dP3$1&cut=dP3$1/7",
    ),
    ("Behemoth", "Other", "Catalan solids", "?shell=oC$1&cut=kT$0"),
];
